import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { Document, Paragraph, TextRun, HeadingLevel, AlignmentType, Packer } from 'docx';
import { saveAs } from 'file-saver';

// Export resume to PDF
export const exportResumeToPDF = async (resume: any, filename?: string): Promise<void> => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  let yPosition = margin;

  const addText = (text: string, fontSize: number = 11, isBold: boolean = false) => {
    pdf.setFontSize(fontSize);
    if (isBold) pdf.setFont('helvetica', 'bold');
    else pdf.setFont('helvetica', 'normal');
    
    const lines = pdf.splitTextToSize(text, pageWidth - 2 * margin);
    lines.forEach((line: string) => {
      if (yPosition > pageHeight - margin) {
        pdf.addPage();
        yPosition = margin;
      }
      pdf.text(line, margin, yPosition);
      yPosition += fontSize * 0.5;
    });
    yPosition += 3;
  };

  addText(resume.title || 'Resume', 18, true);
  
  const sections = resume.sections || [];
  sections.forEach((section: any) => {
    if (!section.isVisible) return;
    addText(section.title || section.type, 14, true);
    const content = typeof section.content === 'string' 
      ? section.content 
      : JSON.stringify(section.content);
    addText(content, 11);
  });

  pdf.save(filename || `resume-${resume.title || 'document'}.pdf`);
};

// Export cover letter to PDF
export const exportCoverLetterToPDF = async (coverLetter: any, filename?: string): Promise<void> => {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  let yPosition = margin;

  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');

  const date = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  pdf.text(date, margin, yPosition);
  yPosition += 10;

  const content = typeof coverLetter === 'string' ? coverLetter : (coverLetter.content || '');
  const lines = pdf.splitTextToSize(content, pageWidth - 2 * margin);
  lines.forEach((line: string) => {
    if (yPosition > pageHeight - margin) {
      pdf.addPage();
      yPosition = margin;
    }
    pdf.text(line, margin, yPosition);
    yPosition += 6;
  });

  pdf.save(filename || `cover-letter-${Date.now()}.pdf`);
};

// Export resume to plain text
export const exportResumeToText = (resume: any, filename?: string): void => {
  let text = `${resume.title || 'Resume'}\n${'='.repeat(50)}\n\n`;
  
  const sections = resume.sections || [];
  sections.forEach((section: any) => {
    if (!section.isVisible) return;
    text += `${section.title || section.type}\n${'-'.repeat(30)}\n`;
    const content = typeof section.content === 'string' 
      ? section.content 
      : JSON.stringify(section.content);
    text += `${content}\n\n`;
  });
  
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || `resume-${resume.title || 'document'}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// Export cover letter to plain text
export const exportCoverLetterToText = (coverLetter: any, filename?: string): void => {
  const content = typeof coverLetter === 'string' ? coverLetter : (coverLetter.content || '');
  const text = `${content}\n\nGenerated by JobHuntr`;
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || `cover-letter-${Date.now()}.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// Export resume to Word (.docx)
export const exportResumeToWord = async (resume: any, filename?: string): Promise<void> => {
  const sections = resume.sections || [];
  const docParagraphs: Paragraph[] = [];

  docParagraphs.push(
    new Paragraph({
      text: resume.title || 'Resume',
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
    })
  );

  sections.forEach((section: any) => {
    if (!section.isVisible) return;

    docParagraphs.push(
      new Paragraph({
        text: section.title || section.type,
        heading: HeadingLevel.HEADING_2,
        spacing: { before: 200, after: 100 },
      })
    );

    const content = typeof section.content === 'string' 
      ? section.content 
      : JSON.stringify(section.content);
    
    docParagraphs.push(
      new Paragraph({
        text: content,
        spacing: { after: 100 },
      })
    );
  });

  const doc = new Document({
    sections: [{
      properties: {},
      children: docParagraphs,
    }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, filename || `resume-${resume.title || 'document'}.docx`);
};

// Export cover letter to Word (.docx)
export const exportCoverLetterToWord = async (coverLetter: any, filename?: string): Promise<void> => {
  const content = typeof coverLetter === 'string' ? coverLetter : (coverLetter.content || '');
  
  const doc = new Document({
    sections: [{
      properties: {},
      children: [
        new Paragraph({
          text: 'Cover Letter',
          heading: HeadingLevel.HEADING_1,
          alignment: AlignmentType.CENTER,
          spacing: { after: 200 },
        }),
        new Paragraph({
          text: content,
          spacing: { after: 100 },
        }),
        new Paragraph({
          children: [
            new TextRun({
              text: 'Generated by JobHuntr',
              italics: true,
            }),
          ],
          alignment: AlignmentType.RIGHT,
        }),
      ],
    }],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, filename || `cover-letter-${Date.now()}.docx`);
};

// Export resume to HTML
export const exportResumeToHTML = (resume: any, filename?: string): void => {
  const sections = resume.sections || [];
  let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${resume.title || 'Resume'}</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; }
    h1 { text-align: center; color: #333; }
    h2 { color: #555; border-bottom: 2px solid #ddd; padding-bottom: 5px; margin-top: 30px; }
    p { line-height: 1.6; color: #666; }
  </style>
</head>
<body>
  <h1>${resume.title || 'Resume'}</h1>`;

  sections.forEach((section: any) => {
    if (!section.isVisible) return;
    html += `<h2>${section.title || section.type}</h2>`;
    const content = typeof section.content === 'string' 
      ? section.content 
      : JSON.stringify(section.content);
    html += `<p>${content.replace(/\n/g, '<br>')}</p>`;
  });

  html += `<p style="text-align: right; font-style: italic; margin-top: 40px;">Generated by JobHuntr</p>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || `resume-${resume.title || 'document'}.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// Export cover letter to HTML
export const exportCoverLetterToHTML = (coverLetter: any, filename?: string): void => {
  const content = typeof coverLetter === 'string' ? coverLetter : (coverLetter.content || '');
  
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cover Letter</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; }
    h1 { text-align: center; color: #333; }
    p { line-height: 1.6; color: #666; white-space: pre-wrap; }
  </style>
</head>
<body>
  <h1>Cover Letter</h1>
  <p>${content}</p>
  <p style="text-align: right; font-style: italic; margin-top: 40px;">Generated by JobHuntr</p>
</body>
</html>`;

  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || `cover-letter-${Date.now()}.html`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

// Export jobs to CSV
export const exportJobsToCSV = (jobs: any[], filename?: string): void => {
  const headers = ['Job Title', 'Company', 'Location', 'Status', 'Salary', 'Applied Date', 'Deadline'];
  const rows = jobs.map(job => [
    job.jobTitle || '',
    job.company?.name || '',
    job.location || '',
    job.status || '',
    job.salaryMin && job.salaryMax ? `${job.salaryMin}-${job.salaryMax}` : '',
    job.appliedDate || '',
    job.applicationDeadline || '',
  ]);

  const csv = [headers, ...rows].map(row => row.join(',')).join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || `jobs-${Date.now()}.csv`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};